USE [master]
GO
/****** Object:  Database [Finance]    Script Date: 31-Mar-22 21:29:44 ******/
CREATE DATABASE [Finance]
GO
ALTER DATABASE [Finance] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Finance] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Finance] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Finance] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Finance] SET ARITHABORT OFF 
GO
ALTER DATABASE [Finance] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Finance] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Finance] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Finance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Finance] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Finance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Finance] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Finance] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Finance] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Finance] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Finance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Finance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Finance] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Finance] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Finance] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Finance] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Finance] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Finance] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Finance] SET  MULTI_USER 
GO
ALTER DATABASE [Finance] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Finance] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Finance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Finance] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Finance] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Finance] SET QUERY_STORE = OFF
GO
USE [Finance]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [Finance]
GO
USE [Finance]
GO
/****** Object:  Table [dbo].[Korisnik]    Script Date: 11.07.2022. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Korisnik](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[JMBG] [nvarchar](13) NOT NULL,
	[Ime] [nvarchar](50) NULL,
	[Prezime] [nvarchar](50) NULL,
	[KorisnickoIme] [nvarchar](50) NULL,
	[Sifra] [nvarchar](50) NULL,
 CONSTRAINT [Korisnik$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
/****** Object:  Table [dbo].[Racun]    Script Date: 11.07.2022. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Racun](
	[Id] [int] NOT NULL,
	[Naziv] [nvarchar](255) NULL,
	[Tip] [nvarchar](255) NULL,
	[Vrednost] [float] NULL,
	[IdKorisnika] [int] NULL,
 CONSTRAINT [Racun$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transakcija]    Script Date: 11.07.2022. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transakcija](
	[Id] [int] NOT NULL,
	[Opis] [nvarchar](255) NULL,
	[Vrednost] [float] NULL,
	[Datum] [datetime] NULL,
	[IdRacun] [int] NOT NULL,
	[IdTipTransakcije] [int] NOT NULL
 CONSTRAINT [Transakcija$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TipTransakcije]    Script Date: 11.07.2022. ******/
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[TipTransakcije](
	[Id] [int] NOT NULL,
	[Naziv] [nvarchar](255) NULL,
 CONSTRAINT [TipTransakcije$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Izvestaj]    Script Date: 11.07.2022. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Izvestaj](
	[IdRacun] [int] NOT NULL,
	[IdTransakcija] [int] NOT NULL,
	[UkupanTrosak] [float] NULL,
	[UkupanPrihod] [float] NULL,
	[UkupanTrosakPoRacunu] [float] NULL,
	[UkupanPrihodPoRacunu] [float] NULL,
	[RacunSaNajvecimTroskovima] [varchar](255) NULL,
	[RacunSaNajmanjimTroskovima] [varchar](255) NULL,
 CONSTRAINT [Predstava$PrimaryKey] PRIMARY KEY CLUSTERED 
(
	[IdRacun] ASC,
	[IdTransakcija] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Korisnik] ON
INSERT INTO [dbo].[Korisnik] (Id, JMBG, Ime, Prezime, KorisnickoIme, Sifra) VALUES(1, '2011998730022', 'Aleksandar', 'Krstic', 'aleksandarkrst', 'aleksandarkrst')
INSERT INTO [dbo].[Korisnik] (Id, JMBG, Ime, Prezime, KorisnickoIme, Sifra) VALUES(2, '1002999482012', 'Nikola', 'Markovic', 'nikola', 'nikola')
SET IDENTITY_INSERT [dbo].[Korisnik] OFF
INSERT INTO [dbo].[TipTransakcije] (Id, Naziv) VALUES(1, 'Trosak')
INSERT INTO [dbo].[TipTransakcije] (Id, Naziv) VALUES(2, 'Prihod')